# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version-file: 'go.mod'
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.27.0
      - name: Install wasm-opt
        run: sudo apt install binaryen
      - name: Get dependencies
        run: go mod download
      - name: Build Wasm
        run: cd lib/wasm && tinygo build -o ../../ui/src/assets/wasm/golib.wasm -target wasm -no-debug  ./main.go
      - name: Optimize Wasm Build
        run: cd ui/src/assets/wasm/ && wasm-opt -Oz golib.wasm -o golib.wasm
      - name: Build Front End
        run: cd ui && yarn install && yarn run package
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      
      - name: Install Guark
        run: go install github.com/guark/guark/cmd/guark@latest
      
      - name: Install Guark Dependencies
        run: sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev build-essential binutils-mingw-w64 wixl 

      - name: Build Linux App
        run: guark build  --target linux --rm

      - name: Archive linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: digame-linux-x64
          path: dist/linux/

      - name: Add i386 Architecture
        run: sudo dpkg --add-architecture i386

      - name: Add Wine Release Key
        run: curl -fsSL  https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -

      - name: Random Wine fix
        run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv F987672F
      - name: Add Wine Repository
        run: sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
      
      - name: Apt Update
        run: sudo apt-get update
      
      - name: Install wine
        run: sudo apt-get install -y --install-recommends winehq-stable winetricks winbind

      - name: Build Windows App
        run: guark build  --target windows --rm

      - name: Archive Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: digame-windows-x64
          path: dist/windows/
